# Generated by Django 3.2.6 on 2021-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instagram_name',
            field=models.CharField(default='off the grid', max_length=50),
        ),
    ]
