# Generated by Django 3.2.6 on 2021-08-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_artist_instagram_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='instagram_name',
        ),
    ]
