# Generated by Django 3.2.6 on 2021-08-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0005_auto_20210814_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='no album title', max_length=15),
        ),
    ]
